package com.toxicflame427.objects.data_models.plant_species

import kotlinx.serialization.Serializable

@Serializable
data class PlantSpecies(
    var apiId: Int,
    val attracts: List<String>,
    val averageHeight: AverageHeight,
    val averageSpread: AverageSpread,
    val commonName: String,
    val companionPlants: List<CompanionPlant>,
    val description: String,
    val floweringMonths: List<String>,
    val floweringSeason: String,
    val fruitIsEdible: Boolean,
    val fullName: String,
    val growingCycle: String,
    val growthRate: Int,
    val hardinessZones: HardinessZones,
    val harvestMonths: List<String>,
    val harvestSeason: String,
    val harvestingInstructions: String,
    val hasFlowers: Boolean,
    val hasSeeds: Boolean,
    val images: List<Image>,
    val isContainerFriendly: Boolean,
    val isDroughtTolerant: Boolean,
    val isFloodTolerant: Boolean,
    val isFrostTolerant: Boolean,
    val isHeatTolerant: Boolean,
    val isIndoorFriendly: Boolean,
    val isInvasive: Boolean,
    val isMedicinal: Boolean,
    val isPoisonousToHumans: Boolean,
    val isPoisonousToPets: Boolean,
    val isSaltTolerant: Boolean,
    val isTropical: Boolean,
    val isVarietyOrCommon: String?,
    val leavesAreEdible: Boolean,
    val maintenanceLevel: Int,
    val maturityTime: MaturityTime,
    val otherNames: List<String>,
    val plantSpacing: PlantSpacing,
    val plantUsage: List<PlantUsage>,
    val plantingInstructions: String,
    val plantingMonths: List<String>,
    val plantingSeason: String,
    val preferredSoil: List<String>,
    val preferredSunlight: List<String>,
    val pruningInstructions: String,
    val scientificName: String,
    val seedGerminationTime: SeedGerminationTime,
    val seedMaturityTime: SeedMaturityTime,
    val seedsAreEdible: Boolean,
    val soilPhProfile: String,
    val sowingInstructions: String,
    val temperatureTolerance: TemperatureTolerance,
    val varietyName: String,
    val wateringInstructions: String
)