package com.toxicflame427.objects.data_models.plant_species

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PlantSpeciesDetails(
    val apiId: Int,
    val averageHeight: AverageHeight,
    val averageSpread: AverageSpread,
    val name: String,
    val description: String,
    val floweringMonths: List<String>,
    val floweringSeason: String,
    val fruitIsEdible: Boolean,
    val growingCycle: String,
    val growthRate: Int,
    val hardinessZones: HardinessZones,
    val harvestMonths: List<String>,
    val harvestSeason: String,
    val harvestingGuide: String,
    val hasFlowers: Boolean,
    val hasSeeds: Boolean,
    val hasCorms: Boolean,
    val images: List<Image>,
    val containerFriendly: Boolean,
    val frostTolerant: Boolean,
    val heatTolerant: Boolean,
    val indoorFriendly: Boolean,
    val medicinal: Boolean,
    val poisonousToHumans: Boolean,
    val poisonousToPets: Boolean,
    val saltTolerant: Boolean,
    val speciesOrVariety: String,
    val leavesAreEdible: Boolean,
    val maintenanceLevel: Int,
    val maturityTime: MaturityTime,
    val otherNames: List<String>,
    val plantSpacing: PlantSpacing,
    val plantingMonths: List<String>,
    val plantingSeason: String,
    val preferredSoil: List<String>,
    val preferredSunlight: List<String>,
    val pruningGuide: String,
    val scientificName: String,
    val seedGerminationTime: SeedGerminationTime,
    val seedsAreEdible: Boolean,
    val soilPh: String,
    val sowingGuide: String,
    val wateringGuide: String
)